### ISSUE TITLE
Nested TabBar in NavigationStack.

### ISSUE THREAD

**Issue by emerson233** [grahammendick/navigation#320]
I am trying to do something like this:
```javascript
const stateNavigator = new StateNavigator([
  {key: 'home'},
  {key: 'notifications'},
  {key: 'tweet', trackCrumbTrail: true},
  {key: 'timeline', trackCrumbTrail: true},
  {key: 'tabs'}
]);
const {home, notifications, tweet, timeline, tabs} = stateNavigator.states;
home.renderScene = () => <Home tweets={getHome()} follows={getFollows()} />;
notifications.renderScene = () => <Notifications follows={getFollows()} />;
tweet.renderScene = ({id}) => <Tweet tweet={getTweet(id)}  />;
timeline.renderScene = ({id}) => <Timeline timeline={getTimeline(id)}  />;

tabs.renderScene = () => {
  return (
    <TabBar bottomTabs={true}>
      <TabBarItem title="Home">
        <Home tweets={getHome()} follows={getFollows()} />
      </TabBarItem>
      <TabBarItem
        title="Notifications"
        badge={getFollows().length}>
        <Notifications follows={getFollows()} />
      </TabBarItem>
    </TabBar>
  );
}

stateNavigator.navigate('tabs');

export default () => {
  return (
    <NavigationHandler stateNavigator={stateNavigator}>
      <NavigationStack />
    </NavigationHandler>
  )
}
```
We don't need TabBar to stay at bottom on android when app is navigated to other pages. What we need is something similar to [hidesBottomBarWhenPushed](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621863-hidesbottombarwhenpushed) on the iOS side.
These codes work as expected when navigating to new pages, but crashed when we navigate back to `tabs` page.

```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4419)
        at android.view.ViewGroup.addView(ViewGroup.java:4260)
        at androidx.viewpager.widget.ViewPager.addView(ViewPager.java:1485)
        at android.view.ViewGroup.addView(ViewGroup.java:4200)
        at android.view.ViewGroup.addView(ViewGroup.java:4173)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1466)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2466)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1483)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2646)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2416)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2372)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6276)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)
```

**Comment by grahammendick** [comment]
Let me see if I understand. You want to navigate from A → B → C where screens A and B have no tabs and screen C has two tabs, for example?

**Comment by emerson233** [comment]
No. I mean after app is launched, it shows `tabs` which contains `twitter list` and `notifications list` at first. And user can click a tweet to navigate to a detail page. In the detail page, we don't want to show a `tab bar` at the bottom of screen.

**Comment by emerson233** [comment]
```javascript
tabs.renderScene = () => {
  return (
    <TabBar bottomTabs={true}>
      <TabBarItem title="Home">
        <Home tweets={getHome()} follows={getFollows()} />
      </TabBarItem>
      <TabBarItem
        title="Notifications"
        badge={getFollows().length}>
        <Notifications follows={getFollows()} />
      </TabBarItem>
    </TabBar>
  );
}
```
Look, I am not placing navigation stack inside `TabBar`. The idea is to wrap the whole `TabBar` into a single navigation stack.

**Comment by grahammendick** [comment]
You can't use the `TabBar`. The `TabBar` expects navigation stacks inside each `TabBarItem`. You just need to put two buttons at the bottom of your first screen and style them to look like tabs.

**Comment by emerson233** [comment]
Alright.
Just curious, why does the `TabBarItem` require a navigation stack inside? I don't see the point.

**Comment by emerson233** [comment]
I see. Thanks for your reply.

**Comment by mpiannucci** [comment]
What happens if you push a tab stack inside another tab stack currently? On iOS you would usually set hidesBottomBarOnPush or whatever its called and they would play nice. Is that supported?

**Comment by grahammendick** [comment]
@mpiannucci I didn't know you could have a `UITabBarController` inside a `UITabBarController`! How does it work? Do the outer tabs get hidden and the inner tabs take over?
The Navigation router doesn't currently support it. Do you want to add support?

**Comment by mpiannucci** [comment]
The typical usage that when you push into the detail tab controller you hide the existing tab bar. 

https://stackoverflow.com/questions/8701362/how-to-hide-the-tabbar-when-push-a-view

I will take a peek at some point to see if I can figure out how it would be done.

**Comment by grahammendick** [comment]
@mpiannucci Cool, let me know if you need a hand

**Comment by mpiannucci** [comment]
I dont know if Ill have time to test at the moment, but I think you could put a check here to see if the subView is of type `NVTabBarView` and if it is, set `hidesBottomBarWhenPushed` on it. Sorry mostly commenting here so I dont forget or in case someone beats me to trying it out

https://github.com/grahammendick/navigation/blob/20de2c34b9e4139a9ca5d1cad3f955423bae034a/NavigationReactNative/src/ios/NVTabBarItemView.m#L44

**Comment by grahammendick** [comment]
@mpiannucci Just to let you know, [l wrapped hidesBottomBarWhenPushed](https://github.com/grahammendick/navigation/pull/417)
