### ISSUE TITLE
Android crash when navigating with the app in the background

### ISSUE THREAD

**Issue by salockhart** [grahammendick/navigation#418]
Hi - I've found a very odd bug and I was wondering if you had some tips.

In my app, we have biometric security that appears when the app is loaded. Depending on the result of that biometric authentication, we then navigate to login (when it fails) or the app (when it succeeds)

The issue appears when we display the native biometric request, and then while it is requesting we close the app. This cancels the biometric request, which counts as a failure, and we try to navigate to the login screen. That navigation happens with the app already in the background.

Doing that, I get the following crash:

```
FATAL EXCEPTION: main
Process: com.app.debug, PID: 17371
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
	at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManagerImpl.java:1672)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1692)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
	at com.navigation.reactnative.NavigationStackView.onAfterUpdateTransaction(NavigationStackView.java:66)
	at com.navigation.reactnative.NavigationStackManager.onAfterUpdateTransaction(NavigationStackManager.java:107)
	at com.navigation.reactnative.NavigationStackManager.onAfterUpdateTransaction(NavigationStackManager.java:15)
	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:51)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:279)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:180)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:786)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:903)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:43)
	at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:861)
	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7860)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

I want to say that this has something to do about attempting a navigation/rerender while in the background, since I saw something similar that was due to trying to listen to and drive state based on AppState. That issue I was able to resolve by removing the state, but this one is trickier. I've been trying to get a reproducible case in one of the sample apps, but no such luck as of yet.

I'm using `expo-local-authentication` for the biometrics, if that helps

**Comment by salockhart** [comment]
This seems like it could be related to https://github.com/grahammendick/navigation/issues/353, but possibly a different way of achieving roughly the same exception. I'm up to date, so it may be something else entirely.

**Comment by grahammendick** [comment]
Thanks for the detailed description and stack trace. It’s great you can reliably recreate it. Can check if state isn’t saved before calling [`commitNow` in the `NavigationStackView`](https://github.com/grahammendick/navigation/blob/9602cfce7b5ee870f6d36c1407a10fb80e9be580/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/NavigationStackView.java#L66), please? This should work but we might need to set the fragment to null if the state is saved. So if it fixes the error make sure you can log and navigate in afterwards

```java
if (!fragment.getChildFragmentManager().isStateSaved())
    transaction.commitNow();
```

**Comment by salockhart** [comment]
Gave it a try, seeing the following exception on start-up now:

```
Exception in native call
java.lang.IllegalStateException: Fragment StackFragment{7ed1595 (57b7dd17-642d-4499-bd06-be00b72aee41) Stack187} has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:923)
	at com.navigation.reactnative.NavigationStackView.onAfterUpdateTransaction(NavigationStackView.java:66)
	at com.navigation.reactnative.NavigationStackManager.onAfterUpdateTransaction(NavigationStackManager.java:107)
	at com.navigation.reactnative.NavigationStackManager.onAfterUpdateTransaction(NavigationStackManager.java:15)
	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:51)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:279)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:180)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:786)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:903)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:43)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:963)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:994)
	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
	at android.view.Choreographer.doFrame(Choreographer.java:725)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7860)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by grahammendick** [comment]
My bad. Can you try this, please?
```java
if (!fragment.isStateSaved())
    transaction.commitNow();
```

**Comment by salockhart** [comment]
For sure! That got us a little further. With that all of the navigations still work, but the bug I had originally is still reproducible, albeit with that same new stacktrace:

```
FATAL EXCEPTION: main
java.lang.IllegalStateException: Fragment StackFragment{58bf28f (fb683d29-0c23-4ddd-8c6b-e8263be98432) Stack187} has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:923)
	at com.navigation.reactnative.FragmentNavigator.canNavigate(FragmentNavigator.java:19)
	at com.navigation.reactnative.NavigationStackView.onAfterUpdateTransaction(NavigationStackView.java:70)
	at com.navigation.reactnative.NavigationStackView.onAttachedToWindow(NavigationStackView.java:90)
	at android.view.View.dispatchAttachedToWindow(View.java:21308)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4239)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:6001)
	at android.view.ViewGroup.addView(ViewGroup.java:5777)
	at com.facebook.react.views.view.ReactViewGroup.addView(ReactViewGroup.java:465)
	at android.view.ViewGroup.addView(ViewGroup.java:5717)
	at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:38)
	at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:19)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:517)
	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:206)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:792)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:903)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:43)
	at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:861)
	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7860)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by grahammendick** [comment]
Ok, try this, please
```java
if (!fragment.isStateSaved())
    transaction.commitNow();
else
    fragment = null;
```

**Comment by salockhart** [comment]
New exception now, so that's progress:

```
FATAL EXCEPTION: main
java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.fragment.app.FragmentManager androidx.fragment.app.Fragment.getChildFragmentManager()' on a null object reference
	at com.navigation.reactnative.FragmentNavigator.canNavigate(FragmentNavigator.java:19)
	at com.navigation.reactnative.NavigationStackView.onAfterUpdateTransaction(NavigationStackView.java:72)
	at com.navigation.reactnative.NavigationStackView.onAttachedToWindow(NavigationStackView.java:92)
	at android.view.View.dispatchAttachedToWindow(View.java:21308)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4239)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:6001)
	at android.view.ViewGroup.addView(ViewGroup.java:5777)
	at com.facebook.react.views.view.ReactViewGroup.addView(ReactViewGroup.java:465)
	at android.view.ViewGroup.addView(ViewGroup.java:5717)
	at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:38)
	at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:19)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:517)
	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:206)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:792)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:903)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:43)
	at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:861)
	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7860)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by grahammendick** [comment]
Ok, let's rejig it a bit so it returns when the fragment is null
```java
if (fragment.isStateSaved()) {
    fragment = null;
    return;
}
transaction.commitNow();
```

**Comment by salockhart** [comment]
That seems to have done it! I'll try and hammer it a bit more. Would you like me to put up a PR?

**Comment by grahammendick** [comment]
Let me know if that works. Then can you try something else too, please? Remove all the changes and  just change the `commitNow` to `commitNowAllowingStateLoss`. Thanks
```java
transaction.commitNowAllowingStateLoss();
```

**Comment by salockhart** [comment]
That second one works too.

**Comment by grahammendick** [comment]
Ok, great. I prefer the second one with `commitNowAllowingStateLoss`. Thanks for offering to do a PR - that would be much appreciated
